
package clientClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KeyValueBaseMasterServiceService", targetNamespace = "http://assignmentImplementation/", wsdlLocation = "http://localhost:8080/keyvalue/kvmaster?wsdl")
public class KeyValueBaseMasterServiceService
    extends Service
{

    private final static URL KEYVALUEBASEMASTERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException KEYVALUEBASEMASTERSERVICESERVICE_EXCEPTION;
    private final static QName KEYVALUEBASEMASTERSERVICESERVICE_QNAME = new QName("http://assignmentImplementation/", "KeyValueBaseMasterServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/keyvalue/kvmaster?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KEYVALUEBASEMASTERSERVICESERVICE_WSDL_LOCATION = url;
        KEYVALUEBASEMASTERSERVICESERVICE_EXCEPTION = e;
    }

    public KeyValueBaseMasterServiceService() {
        super(__getWsdlLocation(), KEYVALUEBASEMASTERSERVICESERVICE_QNAME);
    }

    public KeyValueBaseMasterServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KEYVALUEBASEMASTERSERVICESERVICE_QNAME, features);
    }

    public KeyValueBaseMasterServiceService(URL wsdlLocation) {
        super(wsdlLocation, KEYVALUEBASEMASTERSERVICESERVICE_QNAME);
    }

    public KeyValueBaseMasterServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KEYVALUEBASEMASTERSERVICESERVICE_QNAME, features);
    }

    public KeyValueBaseMasterServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyValueBaseMasterServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KeyValueBaseMasterService
     */
    @WebEndpoint(name = "KeyValueBaseMasterServicePort")
    public KeyValueBaseMasterService getKeyValueBaseMasterServicePort() {
        return super.getPort(new QName("http://assignmentImplementation/", "KeyValueBaseMasterServicePort"), KeyValueBaseMasterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyValueBaseMasterService
     */
    @WebEndpoint(name = "KeyValueBaseMasterServicePort")
    public KeyValueBaseMasterService getKeyValueBaseMasterServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignmentImplementation/", "KeyValueBaseMasterServicePort"), KeyValueBaseMasterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KEYVALUEBASEMASTERSERVICESERVICE_EXCEPTION!= null) {
            throw KEYVALUEBASEMASTERSERVICESERVICE_EXCEPTION;
        }
        return KEYVALUEBASEMASTERSERVICESERVICE_WSDL_LOCATION;
    }

}
