
package clientClasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KeyValueBaseProxyService", targetNamespace = "http://assignmentImplementation/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KeyValueBaseProxyService {


    /**
     * 
     * @param arg0
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/bulkPutRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/bulkPutResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/bulkPut/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/bulkPut/Fault/ServiceNotInitializedException")
    })
    public void bulkPut(
        @WebParam(name = "arg0", partName = "arg0")
        BulkList arg0)
        throws IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/dummyRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/dummyResponse")
    public void dummy(
        @WebParam(name = "arg0", partName = "arg0")
        LengthPredicate arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns assignmentimplementation.ValueListImplArray
     * @throws ServiceNotInitializedException_Exception
     * @throws BeginGreaterThanEndException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/atomicScanRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/atomicScanResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/atomicScan/Fault/IOException"),
        @FaultAction(className = BeginGreaterThanEndException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/atomicScan/Fault/BeginGreaterThanEndException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/atomicScan/Fault/ServiceNotInitializedException")
    })
    public ValueListImplArray atomicScan(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        KeyImpl arg1,
        @WebParam(name = "arg2", partName = "arg2")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ServiceAlreadyInitializedException_Exception
     * @throws ServiceInitializingException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/initRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/initResponse", fault = {
        @FaultAction(className = ServiceAlreadyInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/init/Fault/ServiceAlreadyInitializedException"),
        @FaultAction(className = ServiceInitializingException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/init/Fault/ServiceInitializingException"),
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/init/Fault/FileNotFoundException")
    })
    public void init(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FileNotFoundException_Exception, ServiceAlreadyInitializedException_Exception, ServiceInitializingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/deleteRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/deleteResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/delete/Fault/KeyNotFoundException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/delete/Fault/ServiceNotInitializedException")
    })
    public void delete(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0)
        throws KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     * @throws KeyAlreadyPresentException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/insertRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/insertResponse", fault = {
        @FaultAction(className = KeyAlreadyPresentException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/insert/Fault/KeyAlreadyPresentException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/insert/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/insert/Fault/ServiceNotInitializedException")
    })
    public void insert(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ValueListImpl arg1)
        throws IOException_Exception, KeyAlreadyPresentException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns assignmentimplementation.ValueListImpl
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/readRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/readResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/read/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/read/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/read/Fault/ServiceNotInitializedException")
    })
    public ValueListImpl read(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/updateRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/updateResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/update/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/update/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/update/Fault/ServiceNotInitializedException")
    })
    public void update(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ValueListImpl arg1)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ServiceAlreadyConfiguredException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/configRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/configResponse", fault = {
        @FaultAction(className = ServiceAlreadyConfiguredException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/config/Fault/ServiceAlreadyConfiguredException")
    })
    public void config(
        @WebParam(name = "arg0", partName = "arg0")
        Configuration arg0)
        throws ServiceAlreadyConfiguredException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns assignmentimplementation.ValueListImplArray
     * @throws ServiceNotInitializedException_Exception
     * @throws BeginGreaterThanEndException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseProxyService/scanRequest", output = "http://assignmentImplementation/KeyValueBaseProxyService/scanResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/scan/Fault/IOException"),
        @FaultAction(className = BeginGreaterThanEndException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/scan/Fault/BeginGreaterThanEndException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseProxyService/scan/Fault/ServiceNotInitializedException")
    })
    public ValueListImplArray scan(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        KeyImpl arg1,
        @WebParam(name = "arg2", partName = "arg2")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

}
