
package clientClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KeyValueBaseProxyServiceService", targetNamespace = "http://assignmentImplementation/", wsdlLocation = "http://localhost:8080/keyvalue/kvproxy?wsdl")
public class KeyValueBaseProxyServiceService
    extends Service
{

    private final static URL KEYVALUEBASEPROXYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException KEYVALUEBASEPROXYSERVICESERVICE_EXCEPTION;
    private final static QName KEYVALUEBASEPROXYSERVICESERVICE_QNAME = new QName("http://assignmentImplementation/", "KeyValueBaseProxyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/keyvalue/kvproxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KEYVALUEBASEPROXYSERVICESERVICE_WSDL_LOCATION = url;
        KEYVALUEBASEPROXYSERVICESERVICE_EXCEPTION = e;
    }

    public KeyValueBaseProxyServiceService() {
        super(__getWsdlLocation(), KEYVALUEBASEPROXYSERVICESERVICE_QNAME);
    }

    public KeyValueBaseProxyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KEYVALUEBASEPROXYSERVICESERVICE_QNAME, features);
    }

    public KeyValueBaseProxyServiceService(URL wsdlLocation) {
        super(wsdlLocation, KEYVALUEBASEPROXYSERVICESERVICE_QNAME);
    }

    public KeyValueBaseProxyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KEYVALUEBASEPROXYSERVICESERVICE_QNAME, features);
    }

    public KeyValueBaseProxyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyValueBaseProxyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KeyValueBaseProxyService
     */
    @WebEndpoint(name = "KeyValueBaseProxyServicePort")
    public KeyValueBaseProxyService getKeyValueBaseProxyServicePort() {
        return super.getPort(new QName("http://assignmentImplementation/", "KeyValueBaseProxyServicePort"), KeyValueBaseProxyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyValueBaseProxyService
     */
    @WebEndpoint(name = "KeyValueBaseProxyServicePort")
    public KeyValueBaseProxyService getKeyValueBaseProxyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignmentImplementation/", "KeyValueBaseProxyServicePort"), KeyValueBaseProxyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KEYVALUEBASEPROXYSERVICESERVICE_EXCEPTION!= null) {
            throw KEYVALUEBASEPROXYSERVICESERVICE_EXCEPTION;
        }
        return KEYVALUEBASEPROXYSERVICESERVICE_WSDL_LOCATION;
    }

}
