
package clientClasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KeyValueBaseMasterService", targetNamespace = "http://assignmentImplementation/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KeyValueBaseMasterService {


    /**
     * 
     * @param arg0
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/bulkPutRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/bulkPutResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/bulkPut/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/bulkPut/Fault/ServiceNotInitializedException")
    })
    public void bulkPut(
        @WebParam(name = "arg0", partName = "arg0")
        BulkList arg0)
        throws IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/deleteRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/deleteResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/delete/Fault/KeyNotFoundException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/delete/Fault/ServiceNotInitializedException")
    })
    public void delete(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0)
        throws KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     * @throws KeyAlreadyPresentException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/insertRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/insertResponse", fault = {
        @FaultAction(className = KeyAlreadyPresentException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/insert/Fault/KeyAlreadyPresentException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/insert/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/insert/Fault/ServiceNotInitializedException")
    })
    public void insert(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ValueListImpl arg1)
        throws IOException_Exception, KeyAlreadyPresentException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/updateRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/updateResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/update/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/update/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/update/Fault/ServiceNotInitializedException")
    })
    public void update(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ValueListImpl arg1)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ServiceAlreadyConfiguredException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/configRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/configResponse", fault = {
        @FaultAction(className = ServiceAlreadyConfiguredException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/config/Fault/ServiceAlreadyConfiguredException")
    })
    public void config(
        @WebParam(name = "arg0", partName = "arg0")
        Configuration arg0)
        throws ServiceAlreadyConfiguredException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/dummyRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/dummyResponse")
    public void dummy(
        @WebParam(name = "arg0", partName = "arg0")
        LengthPredicate arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns clientClasses.ArrayReadPair
     * @throws IOException_Exception
     * @throws BeginGreaterThanEndException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/atomicScanRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/atomicScanResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/atomicScan/Fault/IOException"),
        @FaultAction(className = BeginGreaterThanEndException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/atomicScan/Fault/BeginGreaterThanEndException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/atomicScan/Fault/ServiceNotInitializedException")
    })
    public ArrayReadPair atomicScan(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        KeyImpl arg1,
        @WebParam(name = "arg2", partName = "arg2")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws FileNotFoundException_Exception
     * @throws ServiceAlreadyInitializedException_Exception
     * @throws ServiceInitializingException_Exception
     */
    @WebMethod
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/initRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/initResponse", fault = {
        @FaultAction(className = ServiceAlreadyInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/init/Fault/ServiceAlreadyInitializedException"),
        @FaultAction(className = ServiceInitializingException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/init/Fault/ServiceInitializingException"),
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/init/Fault/FileNotFoundException")
    })
    public void init(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws FileNotFoundException_Exception, ServiceAlreadyInitializedException_Exception, ServiceInitializingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns clientClasses.SingleReadPair
     * @throws IOException_Exception
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/readRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/readResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/read/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/read/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/read/Fault/ServiceNotInitializedException")
    })
    public SingleReadPair read(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns clientClasses.ArrayReadPair
     * @throws IOException_Exception
     * @throws BeginGreaterThanEndException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignmentImplementation/KeyValueBaseMasterService/scanRequest", output = "http://assignmentImplementation/KeyValueBaseMasterService/scanResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/scan/Fault/IOException"),
        @FaultAction(className = BeginGreaterThanEndException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/scan/Fault/BeginGreaterThanEndException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://assignmentImplementation/KeyValueBaseMasterService/scan/Fault/ServiceNotInitializedException")
    })
    public ArrayReadPair scan(
        @WebParam(name = "arg0", partName = "arg0")
        KeyImpl arg0,
        @WebParam(name = "arg1", partName = "arg1")
        KeyImpl arg1,
        @WebParam(name = "arg2", partName = "arg2")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

}
